POST http://localhost:3000/api/register
Content-Type: application/json

{
	"name": "Diego Andrade",
	"email": "diego@gmail.com",
	"password": "123456"
}

###

POST http://localhost:3000/api/login
Content-Type: application/json

{    
	"email": "diego@gmail.com",
	"password": "123456"
}

###

POST http://localhost:3000/api/user

###

POST http://localhost:3000/api/logout

###