POST http://localhost:3000/api/login/register
Content-Type: application/json

{
	"name": "Guilherme",
	"email": "gdchiamulera@gmail.com",
	"password": "12345678"
}

###

POST http://localhost:3000/api/login/login
Content-Type: application/json

{    
	"email": "gdchiamulera@gmail.com",
	"password": "12345678"
}

###

POST http://localhost:3000/api/login/checkAuthenticationStatus

###

POST http://localhost:3000/api/login/logout

###